language: node_js
node_js:
  - '7.6'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
install:
  - yarn global add codecov
  - yarn
before_script:
  - cp .env.sample .env
script:
  - yarn test -- --coverage
  - codecov
