language: node_js
node_js:
  - '7.6'
services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
install:
  - yarn global add codecov
  - yarn
before_script:
  - psql -c 'create database test;' -U postgres
  - cp .env.sample .env
  - sleep 10
  - yarn migrate:latest
script:
  - sleep 10
  - yarn test:coverage
  - codecov
