version: '2'

services:
  # SQL and document data store
  db:
    image: postgres:9.6.2-alpine
    volumes:
      - ./scripts/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
     - "5432:5432"
